code: kafkadev
name: kafka-dev
label: Kafka Development Stack
description: Kafka broker, Zookeeper, and Kafka UI for local messaging development
services:
  - name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    env:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  - name: kafka
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    env:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  - name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    env:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    tunnel: true

tags:
  - kafka
  - messaging
  - localdev
version: 1
