name: spring-dev-local
services:
  - name: spring-app
    path: ./spring-boot-app
    dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devdb
    volumes:
      - ./spring-boot-app:/app

  - name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    env:
      POSTGRES_DB: devdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  - name: redis
    image: redis:alpine
    ports:
      - "6379:6379"