// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BuildStack(arg1:string):Promise<void>;

export function BuildStackByStackId(arg1:number):Promise<void>;

export function GetAllStacks():Promise<Array<models.StackUIDto>>;

export function RunStackById(arg1:number):Promise<void>;
