// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildStack(arg1) {
  return window['go']['main']['App']['BuildStack'](arg1);
}

export function RunStackById(arg1) {
  return window['go']['main']['App']['RunStackById'](arg1);
}
